### ISSUE TITLE
test

### ISSUE THREAD

**Issue by yui-shibata** [yui-shibata/dev_lyceum-pokemon-#1]
```yaml
start_date: 2023/5/29
due_date: 2023/5/29
progress: 0.1
parent: 0
```
